version: "3.8"

services:
  mysql:
    image: mysql:5.7
    env_file: ./.env
    volumes:
      - mysql-store:/var/lib/mysql
      # - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_DOCKER_PORT:$MYSQLDB_LOCAL_PORT
  app:
    depends_on:
      - mysql
    build: .
    command: npm start
    env_file: ./.env
    ports:
      - 8686:8080
    environment:
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT

volumes:
  mysql-store:
